version: 2

jobs:
  # this job is not used directly
  build_base:
    machine: true
    environment: &env
      TRAVIS_BRANCH: $CIRCLE_BRANCH
      TRAVIS_PULL_REQUEST: $CI_PULL_REQUEST || "false"
    steps: &ci_steps
      - checkout
      - run: bin/ci prepare_system
      - run: bin/ci prepare_build
      - run: bin/ci build

  build_linux_docker_executor:
    docker:
      - image: jhass/crystal-build-x86_64
        environment:
          LIBRARY_PATH: /usr/lib/crystal/lib/
    steps:
      - checkout
      - run: make std_spec clean
      - run: make crystal std_spec compiler_spec docs
      - run: find samples -name "*.cr" | xargs -L 1 ./bin/crystal build --no-codegen
      - run: ./bin/crystal tool format --check samples spec src

  build_linux:
    machine: true
    environment:
      <<: *env
      TRAVIS_OS_NAME: linux
      ARCH: x86_64
      ARCH_CMD: linux64
    steps: *ci_steps

  build_osx:
    macos:
      xcode: "9.0"
    environment:
      <<: *env
      TRAVIS_OS_NAME: osx
    steps: *ci_steps

workflows:
  version: 2
  build_all_platforms:
    jobs:
      - build_osx
      - build_linux
      - build_linux_docker_executor
